-- Seeds de desenvolvimento local (sem segredos).
-- Objetivo: criar 2 pacientes de teste para validação da Aba 01 (Dados Pessoais).
--
-- Tenant de dev (fixo para facilitar testes):
--   tenant_id = e40046d1-b549-43ac-ad89-626b5b1a52a4
--
-- Pacientes (IDs fixos para navegação):
--   Lucas Mauricio Souza            id = 2ea4508e-4615-4ff0-9d55-68ef15d5dadb
--   Jair Roberto Cunha da Silva     id = f42bcd9e-a4f1-4bdf-8390-a5224f55d953

insert into public.patients (
  id,
  tenant_id,
  full_name,
  social_name,
  nickname,
  salutation,
  cpf,
  cpf_status,
  rg,
  rg_issuer,
  rg_issuer_state,
  rg_issued_at,
  cns,
  national_id,
  date_of_birth,
  gender,
  gender_identity,
  pronouns,
  civil_status,
  nationality,
  preferred_language,
  education_level,
  profession,
  race_color,
  is_pcd,
  birth_place,
  naturalness_city,
  naturalness_state,
  naturalness_country,
  mother_name,
  father_name,
  mobile_phone,
  secondary_phone,
  secondary_phone_type,
  email,
  email_verified,
  mobile_phone_verified,
  pref_contact_method,
  contact_time_preference,
  contact_notes,
  communication_preferences,
  doc_validation_status,
  doc_validation_method,
  doc_validation_source,
  accept_sms,
  accept_email,
  block_marketing,
  marketing_consent_status,
  marketing_consent_source,
  marketing_consent_ip,
  marketing_consent_history,
  photo_path,
  photo_consent,
  record_status,
  onboarding_step,
  is_active,
  external_ids
)
values (
  '2ea4508e-4615-4ff0-9d55-68ef15d5dadb',
  'e40046d1-b549-43ac-ad89-626b5b1a52a4',
  'Lucas Mauricio Souza',
  null,
  'Lucas',
  'Sr.',
  '12345678901',
  'unknown',
  '44556677',
  'SSP-SP',
  'SP',
  '2010-08-15',
  '123456789012345',
  'BR1234567',
  '1992-04-12',
  'M',
  'Cisgenero',
  'Ele/Dele',
  'solteiro',
  'Brasileira',
  'Português',
  'Superior Completo',
  'Enfermeiro',
  'Branca',
  false,
  'Hospital Municipal, São Paulo',
  'São Paulo',
  'SP',
  'Brasil',
  'Sandra Maria Souza',
  'Mauricio Souza',
  '11999998888',
  '1133334444',
  'residencial',
  'lucas.souza@example.com',
  false,
  false,
  'whatsapp',
  'Comercial',
  'Prefere contato via WhatsApp em horário comercial.',
  '{"sms": true, "email": true, "whatsapp": true}'::jsonb,
  'Pendente',
  'Manual',
  'Portal Administrativo (Edicao Manual)',
  true,
  true,
  false,
  'pending',
  'Portal Administrativo (Edicao Manual)',
  '127.0.0.1',
  'Criado via seed local.',
  null,
  false,
  'draft',
  1,
  false,
  '{"legacy_patient_code": "PAC-000001", "source": "seed"}'::jsonb
),
(
  'f42bcd9e-a4f1-4bdf-8390-a5224f55d953',
  'e40046d1-b549-43ac-ad89-626b5b1a52a4',
  'Jair Roberto Cunha da Silva',
  null,
  'Jair',
  'Sr.',
  '98765432100',
  'unknown',
  '99887766',
  'SSP-RJ',
  'RJ',
  '1978-02-20',
  '987654321098765',
  'BR7654321',
  '1958-11-03',
  'M',
  'Cisgenero',
  'Ele/Dele',
  'casado',
  'Brasileira',
  'Português',
  'Medio Completo',
  'Motorista',
  'Parda',
  false,
  'Niterói, RJ',
  'Niterói',
  'RJ',
  'Brasil',
  'Carmem Cunha',
  'Roberto da Silva',
  '21988887777',
  null,
  null,
  'jair.silva@example.com',
  false,
  false,
  'phone',
  'Manha',
  'Prefere ligação pela manhã.',
  '{"sms": false, "email": true, "whatsapp": false}'::jsonb,
  'Pendente',
  'Manual',
  'Importacao de Legado',
  true,
  true,
  false,
  'pending',
  'Importacao de Legado',
  '127.0.0.1',
  'Criado via seed local.',
  null,
  false,
  'draft',
  1,
  false,
  '{"legacy_patient_code": "PAC-000002", "source": "seed"}'::jsonb
)
on conflict (id) do update
set
  tenant_id = excluded.tenant_id,
  full_name = excluded.full_name,
  social_name = excluded.social_name,
  nickname = excluded.nickname,
  salutation = excluded.salutation,
  cpf = excluded.cpf,
  cpf_status = excluded.cpf_status,
  rg = excluded.rg,
  rg_issuer = excluded.rg_issuer,
  rg_issuer_state = excluded.rg_issuer_state,
  rg_issued_at = excluded.rg_issued_at,
  cns = excluded.cns,
  national_id = excluded.national_id,
  date_of_birth = excluded.date_of_birth,
  gender = excluded.gender,
  gender_identity = excluded.gender_identity,
  pronouns = excluded.pronouns,
  civil_status = excluded.civil_status,
  nationality = excluded.nationality,
  preferred_language = excluded.preferred_language,
  education_level = excluded.education_level,
  profession = excluded.profession,
  race_color = excluded.race_color,
  is_pcd = excluded.is_pcd,
  birth_place = excluded.birth_place,
  naturalness_city = excluded.naturalness_city,
  naturalness_state = excluded.naturalness_state,
  naturalness_country = excluded.naturalness_country,
  mother_name = excluded.mother_name,
  father_name = excluded.father_name,
  mobile_phone = excluded.mobile_phone,
  secondary_phone = excluded.secondary_phone,
  secondary_phone_type = excluded.secondary_phone_type,
  email = excluded.email,
  email_verified = excluded.email_verified,
  mobile_phone_verified = excluded.mobile_phone_verified,
  pref_contact_method = excluded.pref_contact_method,
  contact_time_preference = excluded.contact_time_preference,
  contact_notes = excluded.contact_notes,
  communication_preferences = excluded.communication_preferences,
  doc_validation_status = excluded.doc_validation_status,
  doc_validation_method = excluded.doc_validation_method,
  doc_validation_source = excluded.doc_validation_source,
  accept_sms = excluded.accept_sms,
  accept_email = excluded.accept_email,
  block_marketing = excluded.block_marketing,
  marketing_consent_status = excluded.marketing_consent_status,
  marketing_consent_source = excluded.marketing_consent_source,
  marketing_consent_ip = excluded.marketing_consent_ip,
  marketing_consent_history = excluded.marketing_consent_history,
  photo_path = excluded.photo_path,
  photo_consent = excluded.photo_consent,
  record_status = excluded.record_status,
  onboarding_step = excluded.onboarding_step,
  is_active = excluded.is_active,
  external_ids = excluded.external_ids;
